# Generated by Django 5.2 on 2025-04-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.UUIDField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio')], max_length=10)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('contenido_audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=2)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('publico', models.BooleanField(default=False)),
            ],
        ),
    ]
