# Generated by Django 5.2 on 2025-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_hash', models.CharField(max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creditos', models.IntegerField(default=0)),
            ],
        ),
    ]
